# Generated by Django 5.0.6 on 2024-05-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wallet', '0002_stockdata_quantity_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='amount_bought',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
