# Generated by Django 5.0.6 on 2024-06-02 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wallet', '0005_purchasedata_user_stockdata_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedata',
            name='quantity_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
