# Generated by Django 5.0.6 on 2024-05-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wallet', '0003_stockdata_amount_bought'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('quantity_bought', models.IntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='amount_bought',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='open_price',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='quantity_bought',
        ),
    ]
