# Generated by Django 5.0.6 on 2024-06-02 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def create_default_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    default_user = User.objects.filter(username='defaultuser').first()
    if not default_user:
        default_user = User.objects.create_user(username='defaultuser', password='defaultpassword')

    StockData = apps.get_model('app_wallet', 'StockData')
    PurchaseData = apps.get_model('app_wallet', 'PurchaseData')
    
    for stock in StockData.objects.all():
        stock.user = default_user
        stock.save()

    for purchase in PurchaseData.objects.all():
        purchase.user = default_user
        purchase.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_wallet', '0004_purchasedata_remove_stockdata_amount_bought_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RunPython(create_default_user),
    ]
