# Generated by Django 5.0.6 on 2024-06-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wallet', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=10),
        ),
    ]
