# Generated by Django 5.0.6 on 2024-07-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wallet', '0011_remove_transaction_price_walletitself'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletitself',
            name='price_average',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
