# Generated by Django 5.0.6 on 2024-07-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wallet', '0012_walletitself_price_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletitself',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
