# Generated by Django 5.0.6 on 2024-10-25 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_wallet', '0015_alter_stockdata_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockdata',
            unique_together=set(),
        ),
    ]
